refactor: deduplicate i2c parameters
skot/ESP-Miner pull request #188
Opened 2024-05-27 15:55 UTC by tdb3

DS4432U, EMC2101, and INA2101 all contain the same macros for I2C bus usage.
This PR deduplicates code by pulling these i2c macros into a common header.

```c
#define I2C_MASTER_SCL_IO 48        /*!< GPIO number used for I2C master clock */
#define I2C_MASTER_SDA_IO 47        /*!< GPIO number used for I2C master data  */
#define I2C_MASTER_NUM 0            /*!< I2C master i2c port number, the number of i2c peripheral interfaces available will depend on the chip */
#define I2C_MASTER_FREQ_HZ 400000   /*!< I2C master clock frequency */
#define I2C_MASTER_TX_BUF_DISABLE 0 /*!< I2C master doesn't need buffer */
#define I2C_MASTER_RX_BUF_DISABLE 0 /*!< I2C master doesn't need buffer */
#define I2C_MASTER_TIMEOUT_MS 1000
```

Also since DS4432U.c was being touched, opportunistically added missing include for DS4432U.h.

2024-05-29 10:51 UTC, Georges760 requested changes
can you also please remove i2c_master_init(void) from DS4432.c and put it in the main file ?

2024-05-29 10:54 UTC, Georges760 commented
i planned to do such a PR myself, so I will help yours instead

2024-06-04 22:05 UTC, tdb3 commented
> @tdb3 are you able to do the additional commit ? I need it to move forward, sorry to push.
> 
> If you are busy, I can merge as it and do the additional change myself.
> 
> Tell me.

Thanks for pining.  Sorry, I'm a bit busy right now on another project.  I saw a few more opportunities for deduplicating i2c functions beyond `i2c_master_init()` , `i2c_driver_delete()`, `register_read()`, and `register_write_byte()`.  Don't let me hold you up.  I could convert this PR to draft if you'd like or you could merge as-is and one of us could open a follow up PR later.

2024-06-05 07:27 UTC, Georges760 approved these changes

2024-06-05 07:38 UTC, merged