Add retries if the stratum hostname is not found
skot/ESP-Miner pull request #29
Opened 2023-09-07 02:38 UTC by SatoshyBoy

After restoring the Wi-Fi connection due to a power outage, the router may still try to connect to the internet. Therefore, it will fail to solve the IP address, and then the *ipaddr returns a NULL pointer. This will crash the firmware when it reads from a NULL pointer.

2023-09-07 02:46 UTC, benjamin-wilson commented
Why was bDNSFound changed from a bool to an int?

2023-09-08 22:20 UTC, SatoshyBoy commented
Because I need 3 states: waiting, success and failure.

2023-09-10 02:56 UTC, johnny9 requested changes
Don't create merge commits. When updating your PR rebase instead.

2023-09-10 02:56 UTC, johnny9 commented on main/tasks/stratum_task.c
> +static int8_t bDNSFound = 0;
this variable is no longer a bool, give it a clearer name and use and enum for the different states or have a second bool for tracking dns progress

2023-09-10 02:56 UTC, johnny9 commented on components/bm1397/bm1366.c
> +    if (GLOBAL_STATE->valid_jobs[rx_job_id] == 0) {
create a new PR for this

2023-09-21 23:53 UTC, johnny9 commented on components/bm1397/bm1366.c
> +    if (GLOBAL_STATE->valid_jobs[rx_job_id] == 0) {
I merged this piece already. Can you update the PR without it?

2023-10-05 01:55 UTC, closed without merging