Reduce invalid job found from error to info
skot/ESP-Miner pull request #480
Opened 2024-11-15 16:05 UTC by eandersson

While this message can be useful, most commonly it is seen after receiving a mining.notify, or briefly getting disconnected from the pool. changing it from a ERROR to INFO log message to not scare users.

2024-11-22 16:49 UTC, skot commented
a rejected share seems slightly more important than INFO... maybe WARN?

2024-11-22 17:09 UTC, eandersson commented
> a rejected share seems slightly more important than INFO... maybe WARN?

Yea - maybe warning. Most important is that we are consistent across all chip types.

Having that said I have only been able to reproduce these type of errors during race conditions with cleanQueue, and cleanQueue is logged as an error already.

2024-11-30 04:29 UTC, skot requested changes
Plz change to ESP_LOGW, otherwise LGTM

2024-11-30 20:11 UTC, eandersson commented
> Plz change to ESP_LOGW, otherwise LGTM

Updated

2024-12-02 22:42 UTC, WantClue approved these changes

2025-01-22 10:33 UTC, eandersson commented
Rebased

2025-01-27 18:25 UTC, merged